name: validation

# Controls when the workflow will run
on:
  pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a makefile command to build a zip containing the Marketplace template files
      - name: Build app.zip
        run: make dist
